### ISSUE TITLE
Translating html files

### ISSUE THREAD

**Issue by amaurybrisou** [nicksnyder/go-i18n#151] opened 2019-01-21 13:05 UTC
Hello, thank you for this package.

I'd like to know how do you suggest translating a bare html file containing variables tag as html/template handles. 
Should I set a key in my translation file containing the full html ? it'd be a very long key...

```json
{
    "account_created": "<html...... 1000 characters ..... </html>" 
}
```
or translate every keys before I inject them to the html/template.ParseFiles() function ?

I hope I'm clear.

Thanks again

Amaury

**Comment by nicksnyder** [comment] 2019-01-21 21:02
> Should I set a key in my translation file containing the full html ? it'd be a very long key...

No, I wouldn't recommend that.

> translate every keys before I inject them to the html/template.ParseFiles() function

This is one option (i.e. pass struct or map of translated messages to use in the template), or check out the discussion in https://github.com/nicksnyder/go-i18n/issues/150

**Comment by amaurybrisou** [comment] 2019-01-21 21:30
great :) thanks. I definitely think it'd be a good feature to implement.

**Comment by nicksnyder** [comment] 2019-05-09 03:34
Closing this as a duplicate of #150

**Closed by nicksnyder** 2019-05-09 03:34 UTC
