### ISSUE TITLE
Using `description` as MessageID makes goi18n fail

### ISSUE THREAD

**Issue by voroskoi** [nicksnyder/go-i18n#250] opened 2021-04-06 12:35 UTC
Hi,

First of all: Thank You very much for this amazing package.

I have the following `active.en.toml` file:

```toml
description = "Description"

[comment]
one = "Comment"
other = "Comments"
zero = "No Comment"
```

If I run `goi18n.exe merge .\active.en.toml` against it I get the following error message:

`failed to load message file .\active.en.toml: expected value for key "comment" be a string but got map[string]interface {}{"one":"Comment", "other":"Comments", "zero":"No Comment"}`

Changing 'desctiption' in the first line to anything else makes the problem go away.
Calling `LoadMessageFile` method also fails with this input.

I have tried to convert the `toml` file to `yaml` too, but does not help.

I am using `github.com/nicksnyder/go-i18n/v2 v2.1.2`.

**Comment by voroskoi** [comment] 2021-04-15 14:53
Using `other` gives the same result.

**Comment by jmooring** [comment] 2021-05-02 13:37
Duplicate of https://github.com/nicksnyder/go-i18n/issues/209

**Closed** 2021-05-09 12:19 UTC
