### ISSUE TITLE
Any example present how to use message format in JSON

### ISSUE THREAD

**Issue by KingWu** [nicksnyder/go-i18n#238] opened 2020-12-08 06:34 UTC
Hi, i feel confuse on how to use message format in Json. Any demo example?

**Comment by jmooring** [comment] 2021-05-02 13:37
Duplicate of https://github.com/nicksnyder/go-i18n/issues/209

**Comment by CarsonSlovoka** [comment] 2021-05-27 11:46
key point:
> bundle.RegisterUnmarshalFunc("json", json.Unmarshal)

## custom format

default is support TOML, YAML, JSON

If the above format is not satisfied for you, you can define your ``Unmarshal Function``

```go
// UnmarshalFunc unmarshals data into v.
type UnmarshalFunc func(data []byte, v interface{}) error
```

normally v should be something like this:
```go
map[string]interface{}
```

I mean, suppose your contents is below
```
[IDHi]
other="Hi"
```

> https://github.com/nicksnyder/go-i18n/blob/0c6ce6ac1e8c119993c3d5638af4f7cd67ff068a/v2/i18n/parse.go#L42

- buf: file contents ([]byte)
- raw: you must let your unmarshalFunc create an item like that ``{interface{} | map[string]interface{}{"IDHi": Hi}``

**Comment by nicksnyder** [comment] 2024-02-03 04:59
There is a TOML example [here](https://github.com/nicksnyder/go-i18n/blob/main/example/active.en.toml) and you can just convert that file to an equivalent JSON file using a converter like https://pseitz.github.io/toml-to-json-online-converter/ to get the equivalent JSON file:

```json
{
  "HelloPerson": "Hello {{.Name}}",
  "MyUnreadEmails": {
    "description": "The number of unread emails I have",
    "one": "I have {{.PluralCount}} unread email.",
    "other": "I have {{.PluralCount}} unread emails."
  },
  "PersonUnreadEmails": {
    "description": "The number of unread emails a person has",
    "one": "{{.Name}} has {{.UnreadEmailCount}} unread email.",
    "other": "{{.Name}} has {{.UnreadEmailCount}} unread emails."
  }
}
```

There are also a JSON example in this test: https://github.com/nicksnyder/go-i18n/blob/7c6508d75732c7b2b41bc9f46ce9e9a3c7fefff4/i18n/bundle_test.go#L101-L118

**Closed by nicksnyder** 2024-02-03 04:59 UTC
